version: "3.9"

services:
  postgres:
    image: postgres:latest
    hostname: localhost
    container_name: postgres_email_scanner
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email_scanner
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mail_deamon:
    build: .
    ports:
      - "8081:8080"
  mail_service:
    build: .
    ports:
      - "8082:8080"
  telemetry_service:
    build: .
    ports:
      - "8083:8080"
  mail_deamon_redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    stdin_open: true
  clickhouse:
    image: yandex/clickhouse-server:latest
    restart: always
    ports:
      - "8123:8123"  # HTTP порт для ClickHouse
      - "9000:9000"  # TCP порт для ClickHouse

volumes:
  postgres_data:
    driver: local