definitions:
  main.ScanResponse:
    properties:
      is_malicious:
        type: boolean
      reason:
        type: string
    type: object
info:
  contact: {}
paths:
  /scan:
    post:
      consumes:
      - multipart/form-data
      description: Scan a file via multipart/form-data
      parameters:
      - description: Upload file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ScanResponse'
      summary: Scan a file
swagger: "2.0"
